-- migrate:up

CREATE TABLE IF NOT EXISTS core.authz_tuples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_type text NOT NULL,
  object_id text NOT NULL,
  relation text NOT NULL,
  subject_type text NOT NULL,
  subject_id text NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT authz_tuples_subject_type_check
    CHECK (subject_type IN ('user', 'group'))
);

CREATE UNIQUE INDEX IF NOT EXISTS authz_tuples_unique
  ON core.authz_tuples (object_type, object_id, relation, subject_type, subject_id);

CREATE INDEX IF NOT EXISTS authz_tuples_object_idx
  ON core.authz_tuples (object_type, object_id);

CREATE INDEX IF NOT EXISTS authz_tuples_subject_idx
  ON core.authz_tuples (subject_type, subject_id);

-- migrate:down

DROP TABLE IF EXISTS core.authz_tuples;
